# Install docker for Debian OS family
# For the RedHat OS family, it's better to use Podman

- name: "Install docker"
  hosts: all
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true

  tasks:
    - name: Install a list of packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg

    - name: Add Docker GPG apt Key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] "https://download.docker.com/linux/{{ ansible_distribution | lower }}" {{ ansible_distribution_release | lower }} stable
        state: present

    - name: Debian-Based | Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
